[package]
name = "raion"
version = "0.1.0"
edition = "2021"

[dependencies]
inline_colorization = "0.1.6"
toml = "0.8.19"

[dependencies.common]
path = "../common"

[dependencies.xxhash-rust]
version = "0.8.12"
features = ["xxh3", "const_xxh3"]
